# -*- coding: utf-8 -*-
"""W11_확인문제_Huffman_student.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135BrYlIe2Ty5FvUwLIbdbx1tL6h_jxVA

# 다음 표의 캐릭터와 빈도수로 얻어진 값을 호프만 코드로 만드는 파이썬 클래스 HuffmanNode 를 작성하라. 아래 클래스 틀을 활용하라.
"""

class HuffmanNode:
    def __init__(self, frequency, symbol=None, left=None, right=None):
        self.frequency = frequency
        self.symbol = symbol
        self.left = left
        self.right = right

    # Helper method to check if a node is a leaf (has no children)
    def is_leaf(self):
        return self.left is None and self.right is None


class HuffmanCoding:
    def __init__(self, frequencies): # frequencies -> dict, with char: freq
        # Initialize with a list of Huffman nodes for each character
        self.nodes = [HuffmanNode(freq, symbol) for symbol, freq in frequencies.items()]
        self.nodes = sorted(self.nodes, key=lambda x: x.frequency)

        while len(self.nodes) > 1 :
          min1 = self.nodes[0]
          min2 = self.nodes[1]
          self.nodes = self.nodes[2:]
          node = HuffmanNode(min1.frequency+min2.frequency, "temp", min1, min2)
          self.nodes.append(node)
          self.nodes = sorted(self.nodes, key=lambda x: x.frequency)

        self.root = node


    def get_codes(self, node, code = '', code_dict = {}) :
      if node.is_leaf() :
        code_dict.update({node.symbol:code})
        return code_dict
      left = node.left
      right = node.right
      self.get_codes(left, code + '1', code_dict)
      self.get_codes(right, code + '0', code_dict)
      return code_dict



# Example usage
if __name__ == "__main__":
    # Input frequencies as per Table 9.1.2
    frequencies = {
        '!': 2,
        '@': 3,
        '#': 7,
        '$': 8,
        '%': 12
    }

    # Create HuffmanCoding instance and get the codes
    huffman_coding = HuffmanCoding(frequencies)
    codes = huffman_coding.get_codes(huffman_coding.root)

    # Output the resulting Huffman codes
    print("Huffman Codes for the given frequencies:")
    for symbol, code in codes.items():
        print(f"{symbol}: {code}")

